name: Lighthouse
on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://www.foo.software,https://www.google.com'
  # You may pin to the exact commit or the version.
  # uses: foo-software/lighthouse-check-action@f78f162ef0ecd48a18244c427959f0b79ef4d553
